export interface QuestionItem {
  id: number;
  letter: string;
  category: 'verbos' | 'alimentos';
  categoryLabelEs: string;
  categoryLabelHy: string;
  spanish: string;
  armenian: string;
  options: {
    key: 'A' | 'B' | 'C' | 'D';
    text: string;
  }[];
  correctKey: 'A' | 'B' | 'C' | 'D';
  correctNote?: string;
}

// 25 letters of Spanish Pasapalabra Rosco (A through Z, including Ñ, excluding rarely used K, W):
// A, B, C, D, E, F, G, H, I, J, L, M, N, Ñ, O, P, Q, R, S, T, U, V, X, Y, Z
export const ROSCO_SPANISH_LETTERS = [
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
  'L', 'M', 'N', 'Ñ', 'O', 'P', 'Q', 'R', 'S', 'T',
  'U', 'V', 'X', 'Y', 'Z'
];

export interface TongueTwister {
  id: number;
  spanish: string;
  armenian: string;
}

export const QUESTIONS_DATA_RAW: Omit<QuestionItem, 'letter'>[] = [
  {
    id: 1,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Yo ___ música todos los días.',
    armenian: 'Ես ամեն օր երաժշտություն եմ լսում։',
    options: [
      { key: 'A', text: 'oigo' },
      { key: 'B', text: 'escucho' },
      { key: 'C', text: 'sé' },
      { key: 'D', text: 'conozco' },
    ],
    correctKey: 'B',
    correctNote: 'escucho (ուշադիր լսել / երաժշտություն ունկնդրել)',
  },
  {
    id: 2,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'No te ___ bien. ¿Puedes hablar más alto?',
    armenian: 'Ես քեզ լավ չեմ լսում։ Կարո՞ղ ես ավելի բարձր խոսել։',
    options: [
      { key: 'A', text: 'escucho' },
      { key: 'B', text: 'conozco' },
      { key: 'C', text: 'oigo' },
      { key: 'D', text: 'sé' },
    ],
    correctKey: 'C',
    correctNote: 'oigo (ֆիզիկապես լսել / ականջին հասնել)',
  },
  {
    id: 3,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Yo ___ hablar español.',
    armenian: 'Ես իսպաներեն խոսել գիտեմ։',
    options: [
      { key: 'A', text: 'conozco' },
      { key: 'B', text: 'sé' },
      { key: 'C', text: 'oigo' },
      { key: 'D', text: 'escucho' },
    ],
    correctKey: 'B',
    correctNote: 'sé (կարողություն, հմտություն իմանալ)',
  },
  {
    id: 4,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: '¿___ a María?',
    armenian: 'Դու ճանաչո՞ւմ ես Մարիային։',
    options: [
      { key: 'A', text: 'Sabes' },
      { key: 'B', text: 'Oyes' },
      { key: 'C', text: 'Conoces' },
      { key: 'D', text: 'Escuchas' },
    ],
    correctKey: 'C',
    correctNote: 'Conoces (մարդու ճանաչել)',
  },
  {
    id: 5,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Marta ___ la radio por la mañana.',
    armenian: 'Մարտան առավոտյան ռադիո է լսում։',
    options: [
      { key: 'A', text: 'escucha' },
      { key: 'B', text: 'oye' },
      { key: 'C', text: 'sabe' },
      { key: 'D', text: 'conoce' },
    ],
    correctKey: 'A',
    correctNote: 'escucha (ռադիո լսել)',
  },
  {
    id: 6,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Desde aquí no ___ lo que dice el profesor.',
    armenian: 'Այստեղից չեմ լսում, թե ինչ է ասում ուսուցիչը։',
    options: [
      { key: 'A', text: 'conozco' },
      { key: 'B', text: 'sé' },
      { key: 'C', text: 'escucho' },
      { key: 'D', text: 'oigo' },
    ],
    correctKey: 'D',
    correctNote: 'oigo (ձայնը չի հասնում)',
  },
  {
    id: 7,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: '¿___ dónde está la biblioteca?',
    armenian: 'Գիտե՞ս՝ որտեղ է գրադարանը։',
    options: [
      { key: 'A', text: 'Conoces' },
      { key: 'B', text: 'Sabes' },
      { key: 'C', text: 'Oyes' },
      { key: 'D', text: 'Escuchas' },
    ],
    correctKey: 'B',
    correctNote: 'Sabes (տեղեկություն իմանալ)',
  },
  {
    id: 8,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Nosotros ___ muy bien Barcelona.',
    armenian: 'Մենք շատ լավ ճանաչում ենք Բարսելոնան։',
    options: [
      { key: 'A', text: 'sabemos' },
      { key: 'B', text: 'escuchamos' },
      { key: 'C', text: 'conocemos' },
      { key: 'D', text: 'oímos' },
    ],
    correctKey: 'C',
    correctNote: 'conocemos (քաղաքին, վայրին ծանոթ լինել)',
  },
  {
    id: 9,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: '¡Silencio! Quiero ___ lo que dice.',
    armenian: 'Լռություն։ Ուզում եմ լսել, թե ինչ է նա ասում։',
    options: [
      { key: 'A', text: 'saber' },
      { key: 'B', text: 'escuchar' },
      { key: 'C', text: 'conocer' },
      { key: 'D', text: 'sabiendo' },
    ],
    correctKey: 'B',
    correctNote: 'escuchar (ուշադիր լսել)',
  },
  {
    id: 10,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: '¿___ ese ruido?',
    armenian: 'Լսո՞ւմ ես այդ աղմուկը։',
    options: [
      { key: 'A', text: 'Sabes' },
      { key: 'B', text: 'Conoces' },
      { key: 'C', text: 'Oyes' },
      { key: 'D', text: 'Escuchas a' },
    ],
    correctKey: 'C',
    correctNote: 'Oyes (աղմուկ լսել)',
  },
  {
    id: 11,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'No ___ la respuesta.',
    armenian: 'Ես պատասխանը չգիտեմ։',
    options: [
      { key: 'A', text: 'conozco' },
      { key: 'B', text: 'sé' },
      { key: 'C', text: 'escucho' },
      { key: 'D', text: 'oigo' },
    ],
    correctKey: 'B',
    correctNote: 'sé (պատասխանը իմանալ)',
  },
  {
    id: 12,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Pedro ___ a muchos músicos.',
    armenian: 'Պեդրոն շատ երաժիշտների է ճանաչում։',
    options: [
      { key: 'A', text: 'sabe' },
      { key: 'B', text: 'conoce' },
      { key: 'C', text: 'oye' },
      { key: 'D', text: 'escucha' },
    ],
    correctKey: 'B',
    correctNote: 'conoce (մարդկանց ճանաչել)',
  },
  {
    id: 13,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Me gusta ___ podcasts mientras camino.',
    armenian: 'Ես սիրում եմ քայլելիս փոդքասթներ լսել։',
    options: [
      { key: 'A', text: 'oír a' },
      { key: 'B', text: 'conocer' },
      { key: 'C', text: 'escuchar' },
      { key: 'D', text: 'saber' },
    ],
    correctKey: 'C',
    correctNote: 'escuchar (փոդքասթներ ունկնդրել)',
  },
  {
    id: 14,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: '¿___ cocinar paella?',
    armenian: 'Գիտե՞ս պաեյա պատրաստել։',
    options: [
      { key: 'A', text: 'Conoces' },
      { key: 'B', text: 'Sabes' },
      { key: 'C', text: 'Escuchas' },
      { key: 'D', text: 'Oyes' },
    ],
    correctKey: 'B',
    correctNote: 'Sabes (ինչ-որ բան անել իմանալ)',
  },
  {
    id: 15,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Yo no ___ personalmente a ese profesor.',
    armenian: 'Ես անձամբ չեմ ճանաչում այդ ուսուցչին։',
    options: [
      { key: 'A', text: 'sé' },
      { key: 'B', text: 'oigo' },
      { key: 'C', text: 'conozco' },
      { key: 'D', text: 'escucho' },
    ],
    correctKey: 'C',
    correctNote: 'conozco (անձամբ ճանաչել)',
  },
  {
    id: 16,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Desde mi habitación ___ a los vecinos.',
    armenian: 'Իմ սենյակից լսում եմ հարևաններին։',
    options: [
      { key: 'A', text: 'sé' },
      { key: 'B', text: 'conozco' },
      { key: 'C', text: 'oigo' },
      { key: 'D', text: 'escucho música' },
    ],
    correctKey: 'C',
    correctNote: 'oigo (ակամա լսել)',
  },
  {
    id: 17,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Ana ___ muy bien esta ciudad.',
    armenian: 'Անան շատ լավ ճանաչում է այս քաղաքը։',
    options: [
      { key: 'A', text: 'conoce' },
      { key: 'B', text: 'sabe' },
      { key: 'C', text: 'oye' },
      { key: 'D', text: 'escucha' },
    ],
    correctKey: 'A',
    correctNote: 'conoce (քաղաք ճանաչել)',
  },
  {
    id: 18,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'No ___ qué hacer.',
    armenian: 'Չգիտեմ՝ ինչ անել։',
    options: [
      { key: 'A', text: 'conozco' },
      { key: 'B', text: 'escucho' },
      { key: 'C', text: 'sé' },
      { key: 'D', text: 'oigo' },
    ],
    correctKey: 'C',
    correctNote: 'sé (չգիտեմ)',
  },
  {
    id: 19,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Los estudiantes ___ al profesor con atención.',
    armenian: 'Աշակերտները ուշադրությամբ լսում են ուսուցչին։',
    options: [
      { key: 'A', text: 'oyen' },
      { key: 'B', text: 'escuchan' },
      { key: 'C', text: 'saben' },
      { key: 'D', text: 'conocen' },
    ],
    correctKey: 'B',
    correctNote: 'escuchan (ուշադիր լսել)',
  },
  {
    id: 20,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: '¿___ esta canción?',
    armenian: 'Դու ճանաչո՞ւմ ես այս երգը։',
    options: [
      { key: 'A', text: 'Conoces' },
      { key: 'B', text: 'Sabes' },
      { key: 'C', text: 'Oyes' },
      { key: 'D', text: 'Escuchas' },
    ],
    correctKey: 'A',
    correctNote: 'Conoces (երգ ճանաչել/ծանոթ լինել)',
  },
  {
    id: 21,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Yo ___ que mañana no hay clase.',
    armenian: 'Ես գիտեմ, որ վաղը դաս չկա։',
    options: [
      { key: 'A', text: 'conozco' },
      { key: 'B', text: 'escucho' },
      { key: 'C', text: 'sé' },
      { key: 'D', text: 'oigo' },
    ],
    correctKey: 'C',
    correctNote: 'sé (տեղյակ եմ, գիտեմ որ...)',
  },
  {
    id: 22,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'No puedo dormir porque ___ mucho ruido.',
    armenian: 'Չեմ կարող քնել, որովհետև շատ աղմուկ եմ լսում։',
    options: [
      { key: 'A', text: 'conozco' },
      { key: 'B', text: 'sé' },
      { key: 'C', text: 'oigo' },
      { key: 'D', text: 'escucho música' },
    ],
    correctKey: 'C',
    correctNote: 'oigo (աղմուկ լսել)',
  },
  {
    id: 23,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: '¿Quieres ___ esta canción conmigo?',
    armenian: 'Ուզո՞ւմ ես ինձ հետ այս երգը լսել։',
    options: [
      { key: 'A', text: 'conocer' },
      { key: 'B', text: 'escuchar' },
      { key: 'C', text: 'saber' },
      { key: 'D', text: 'oír a' },
    ],
    correctKey: 'B',
    correctNote: 'escuchar (երգը միասին ունկնդրել)',
  },
  {
    id: 24,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: '¿___ a tu nuevo compañero de clase?',
    armenian: 'Ճանաչո՞ւմ ես քո նոր դասընկերոջը։',
    options: [
      { key: 'A', text: 'Sabes' },
      { key: 'B', text: 'Conoces' },
      { key: 'C', text: 'Escuchas' },
      { key: 'D', text: 'Oyes' },
    ],
    correctKey: 'B',
    correctNote: 'Conoces (դասընկերոջը ճանաչել)',
  },
  {
    id: 25,
    category: 'verbos',
    categoryLabelEs: 'Oír / Escuchar / Saber / Conocer',
    categoryLabelHy: 'Բայեր՝ Oír / Escuchar / Saber / Conocer',
    spanish: 'Ella ___ nadar muy bien.',
    armenian: 'Նա շատ լավ լողալ գիտի։',
    options: [
      { key: 'A', text: 'sabe' },
      { key: 'B', text: 'conoce' },
      { key: 'C', text: 'escucha' },
      { key: 'D', text: 'oye' },
    ],
    correctKey: 'A',
    correctNote: 'sabe (հմտություն իմանալ)',
  },
  {
    id: 26,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál de estos es una fruta?',
    armenian: 'Սրանցից ո՞րն է միրգ։',
    options: [
      { key: 'A', text: 'zanahoria' },
      { key: 'B', text: 'manzana' },
      { key: 'C', text: 'cebolla' },
      { key: 'D', text: 'patata' },
    ],
    correctKey: 'B',
    correctNote: 'manzana — խնձոր',
  },
  {
    id: 27,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál es una verdura?',
    armenian: 'Ո՞րն է բանջարեղեն։',
    options: [
      { key: 'A', text: 'pera' },
      { key: 'B', text: 'plátano' },
      { key: 'C', text: 'zanahoria' },
      { key: 'D', text: 'melocotón' },
    ],
    correctKey: 'C',
    correctNote: 'zanahoria — գազար',
  },
  {
    id: 28,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: 'La fresa es...',
    armenian: 'Ելակը...',
    options: [
      { key: 'A', text: 'una fruta' },
      { key: 'B', text: 'una bebida' },
      { key: 'C', text: 'una carne' },
      { key: 'D', text: 'un pan' },
    ],
    correctKey: 'A',
    correctNote: 'una fruta (միրգ/հատապտուղ)',
  },
  {
    id: 29,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cómo se dice «огурец» en español?',
    armenian: 'Ինչպե՞ս է «վարունգը» իսպաներեն։',
    options: [
      { key: 'A', text: 'pepino' },
      { key: 'B', text: 'pimiento' },
      { key: 'C', text: 'tomate' },
      { key: 'D', text: 'ajo' },
    ],
    correctKey: 'A',
    correctNote: 'pepino — վարունգ',
  },
  {
    id: 30,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cómo se dice «персик»?',
    armenian: 'Ինչպե՞ս է «դեղձը» իսպաներեն։',
    options: [
      { key: 'A', text: 'ciruela' },
      { key: 'B', text: 'melocotón' },
      { key: 'C', text: 'pera' },
      { key: 'D', text: 'cereza' },
    ],
    correctKey: 'B',
    correctNote: 'melocotón — դեղձ',
  },
  {
    id: 31,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál de estos es amarillo normalmente?',
    armenian: 'Սրանցից ո՞րն է սովորաբար դեղին։',
    options: [
      { key: 'A', text: 'plátano' },
      { key: 'B', text: 'berenjena' },
      { key: 'C', text: 'fresa' },
      { key: 'D', text: 'cereza' },
    ],
    correctKey: 'A',
    correctNote: 'plátano — բանան',
  },
  {
    id: 32,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: 'La berenjena normalmente es...',
    armenian: 'Սմբուկը սովորաբար...',
    options: [
      { key: 'A', text: 'morada' },
      { key: 'B', text: 'naranja' },
      { key: 'C', text: 'blanca' },
      { key: 'D', text: 'amarilla' },
    ],
    correctKey: 'A',
    correctNote: 'morada — մանուշակագույն',
  },
  {
    id: 33,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál tiene muchas hojas verdes?',
    armenian: 'Ո՞րն ունի շատ կանաչ տերևներ։',
    options: [
      { key: 'A', text: 'lechuga' },
      { key: 'B', text: 'manzana' },
      { key: 'C', text: 'plátano' },
      { key: 'D', text: 'limón' },
    ],
    correctKey: 'A',
    correctNote: 'lechuga — հազար (սալաթ)',
  },
  {
    id: 34,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál de estos es cítrico?',
    armenian: 'Սրանցից ո՞րն է ցիտրուսային միրգ։',
    options: [
      { key: 'A', text: 'naranja' },
      { key: 'B', text: 'patata' },
      { key: 'C', text: 'cebolla' },
      { key: 'D', text: 'zanahoria' },
    ],
    correctKey: 'A',
    correctNote: 'naranja — նարինջ',
  },
  {
    id: 35,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cómo se dice «лук»?',
    armenian: 'Ինչպե՞ս է «սոխը» իսպաներեն։',
    options: [
      { key: 'A', text: 'ajo' },
      { key: 'B', text: 'cebolla' },
      { key: 'C', text: 'col' },
      { key: 'D', text: 'pepino' },
    ],
    correctKey: 'B',
    correctNote: 'cebolla — սոխ',
  },
  {
    id: 36,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cómo se dice «чеснок»?',
    armenian: 'Ինչպե՞ս է «սխտորը» իսպաներեն։',
    options: [
      { key: 'A', text: 'ajo' },
      { key: 'B', text: 'apio' },
      { key: 'C', text: 'perejil' },
      { key: 'D', text: 'puerro' },
    ],
    correctKey: 'A',
    correctNote: 'ajo — սխտոր',
  },
  {
    id: 37,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál de estos crece bajo tierra?',
    armenian: 'Սրանցից ո՞րն է աճում հողի տակ։',
    options: [
      { key: 'A', text: 'patata' },
      { key: 'B', text: 'manzana' },
      { key: 'C', text: 'tomate' },
      { key: 'D', text: 'uva' },
    ],
    correctKey: 'A',
    correctNote: 'patata — կարտոֆիլ',
  },
  {
    id: 38,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Qué fruta se usa mucho para hacer zumo?',
    armenian: 'Ո՞ր միրգն են հաճախ օգտագործում հյութ պատրաստելու համար։',
    options: [
      { key: 'A', text: 'naranja' },
      { key: 'B', text: 'cebolla' },
      { key: 'C', text: 'ajo' },
      { key: 'D', text: 'berenjena' },
    ],
    correctKey: 'A',
    correctNote: 'naranja — նարինջ',
  },
  {
    id: 39,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cómo se dice «виноград»?',
    armenian: 'Ինչպե՞ս է «խաղողը» իսպաներեն։',
    options: [
      { key: 'A', text: 'uva' },
      { key: 'B', text: 'pera' },
      { key: 'C', text: 'ciruela' },
      { key: 'D', text: 'sandía' },
    ],
    correctKey: 'A',
    correctNote: 'uva — խաղող',
  },
  {
    id: 40,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál es grande, verde por fuera y roja por dentro?',
    armenian: 'Ո՞րն է դրսից կանաչ, ներսից կարմիր և մեծ։',
    options: [
      { key: 'A', text: 'sandía' },
      { key: 'B', text: 'limón' },
      { key: 'C', text: 'pera' },
      { key: 'D', text: 'cereza' },
    ],
    correctKey: 'A',
    correctNote: 'sandía — ձմերուկ',
  },
  {
    id: 41,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál es pequeña y normalmente roja?',
    armenian: 'Ո՞րն է փոքր և սովորաբար կարմիր։',
    options: [
      { key: 'A', text: 'cereza' },
      { key: 'B', text: 'melón' },
      { key: 'C', text: 'piña' },
      { key: 'D', text: 'plátano' },
    ],
    correctKey: 'A',
    correctNote: 'cereza — բալ / կեռաս',
  },
  {
    id: 42,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Qué fruta tiene una corona de hojas?',
    armenian: 'Ո՞ր միրգն ունի տերևներից «թագ»։',
    options: [
      { key: 'A', text: 'piña' },
      { key: 'B', text: 'pera' },
      { key: 'C', text: 'manzana' },
      { key: 'D', text: 'ciruela' },
    ],
    correctKey: 'A',
    correctNote: 'piña — արքայախնձոր (անանաս)',
  },
  {
    id: 43,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál de estas verduras es naranja?',
    armenian: 'Այս բանջարեղեններից ո՞րն է նարնջագույն։',
    options: [
      { key: 'A', text: 'zanahoria' },
      { key: 'B', text: 'pepino' },
      { key: 'C', text: 'lechuga' },
      { key: 'D', text: 'berenjena' },
    ],
    correctKey: 'A',
    correctNote: 'zanahoria — գազար',
  },
  {
    id: 44,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cómo se dice «капуста»?',
    armenian: 'Ինչպե՞ս է «կաղամբը» իսպաներեն։',
    options: [
      { key: 'A', text: 'col' },
      { key: 'B', text: 'ajo' },
      { key: 'C', text: 'cebolla' },
      { key: 'D', text: 'pimiento' },
    ],
    correctKey: 'A',
    correctNote: 'col — կաղամբ',
  },
  {
    id: 45,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál de estos puede ser rojo, verde o amarillo?',
    armenian: 'Սրանցից ո՞րը կարող է լինել կարմիր, կանաչ կամ դեղին։',
    options: [
      { key: 'A', text: 'pimiento' },
      { key: 'B', text: 'ajo' },
      { key: 'C', text: 'patata' },
      { key: 'D', text: 'berenjena' },
    ],
    correctKey: 'A',
    correctNote: 'pimiento — պղպեղ',
  },
  {
    id: 46,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Qué fruta tiene muchas semillas pequeñas por fuera?',
    armenian: 'Ո՞ր միրգն ունի շատ փոքր սերմեր արտաքին մակերեսին։',
    options: [
      { key: 'A', text: 'fresa' },
      { key: 'B', text: 'pera' },
      { key: 'C', text: 'naranja' },
      { key: 'D', text: 'melón' },
    ],
    correctKey: 'A',
    correctNote: 'fresa — ելակ',
  },
  {
    id: 47,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cómo se dice «слива»?',
    armenian: 'Ինչպե՞ս է «սալորը» իսպաներեն։',
    options: [
      { key: 'A', text: 'ciruela' },
      { key: 'B', text: 'cereza' },
      { key: 'C', text: 'pera' },
      { key: 'D', text: 'uva' },
    ],
    correctKey: 'A',
    correctNote: 'ciruela — սալոր',
  },
  {
    id: 48,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál de estos se usa mucho en ensaladas?',
    armenian: 'Սրանցից ո՞րն են հաճախ օգտագործում աղցաններում։',
    options: [
      { key: 'A', text: 'tomate' },
      { key: 'B', text: 'plátano' },
      { key: 'C', text: 'melocotón' },
      { key: 'D', text: 'sandía' },
    ],
    correctKey: 'A',
    correctNote: 'tomate — լոլիկ',
  },
  {
    id: 49,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Qué fruta es normalmente verde o amarilla y tiene forma alargada abajo?',
    armenian: 'Ո՞ր միրգն է սովորաբար կանաչ կամ դեղին և ներքևի մասում երկարավուն ձև ունի։',
    options: [
      { key: 'A', text: 'pera' },
      { key: 'B', text: 'cereza' },
      { key: 'C', text: 'fresa' },
      { key: 'D', text: 'naranja' },
    ],
    correctKey: 'A',
    correctNote: 'pera — տանձ',
  },
  {
    id: 50,
    category: 'alimentos',
    categoryLabelEs: 'Frutas y Verduras',
    categoryLabelHy: 'Մրգեր և Բանջարեղեն',
    spanish: '¿Cuál sería una buena combinación para una ensalada?',
    armenian: 'Ո՞ր տարբերակն է լավ համադրություն աղցանի համար։',
    options: [
      { key: 'A', text: 'tomate + pepino + cebolla' },
      { key: 'B', text: 'plátano + ajo + chocolate' },
      { key: 'C', text: 'sandía + patata + café' },
      { key: 'D', text: 'pera + cebolla + leche' },
    ],
    correctKey: 'A',
    correctNote: 'tomate + pepino + cebolla (լոլիկ + վարունգ + սոխ)',
  },
];

export const QUESTIONS_DATA: QuestionItem[] = QUESTIONS_DATA_RAW.map((q, index) => {
  // 25 letters for part 1 (1..25), 25 letters for part 2 (26..50)
  const letter = ROSCO_SPANISH_LETTERS[index % 25];
  return {
    ...q,
    letter,
  };
});

export const TONGUE_TWISTERS_DATA: TongueTwister[] = [
  {
    id: 1,
    spanish: 'Pablo prepara pan para Pedro, pero Pedro prefiere pan con pera.',
    armenian: 'Պաբլոն հաց է պատրաստում Պեդրոյի համար, բայց Պեդրոն նախընտրում է տանձով հաց։',
  },
  {
    id: 2,
    spanish: 'Rosa riega rosas rojas mientras Ramón recoge ramas alrededor del río.',
    armenian: 'Ռոսան ջրում է կարմիր վարդերը, մինչ Ռամոնը գետի շուրջը ճյուղեր է հավաքում։',
  },
  {
    id: 3,
    spanish: 'Carlos cocina cuatro croquetas crujientes para Carmen y Claudia.',
    armenian: 'Կառլոսը չորս խրթխրթան կրոկետ է պատրաստում Կարմենի և Կլաուդիայի համար։',
  },
  {
    id: 4,
    spanish: 'Lucía limpia lentamente las largas lámparas del salón.',
    armenian: 'Լուսիան դանդաղ մաքրում է հյուրասենյակի երկար լամպերը։',
  },
  {
    id: 5,
    spanish: 'Jorge juega con Javier junto al jardín de Julia.',
    armenian: 'Խորխեն խաղում է Խավիերի հետ Խուլիայի այգու մոտ։',
  },
  {
    id: 6,
    spanish: 'Sergio sirve seis sopas suaves sobre siete platos.',
    armenian: 'Սերխիոն վեց թեթև ապուր է մատուցում յոթ ափսեի վրա։',
  },
  {
    id: 7,
    spanish: 'Miguel mezcla miel, mango y melón mientras Marta mira.',
    armenian: 'Միգելը խառնում է մեղր, մանգո և սեխ, մինչ Մարտան նայում է։',
  },
  {
    id: 8,
    spanish: 'Daniel dibuja dos delfines divertidos dentro de dos círculos.',
    armenian: 'Դանիելը երկու զվարճալի դելֆին է նկարում երկու շրջանների մեջ։',
  },
  {
    id: 9,
    spanish: 'Fernando fotografía flores frente a la fuente de Federico.',
    armenian: 'Ֆերնանդոն լուսանկարում է ծաղիկները Ֆեդերիկոյի շատրվանի առաջ։',
  },
  {
    id: 10,
    spanish: 'Antonio abre ocho cajas azules antes de almorzar.',
    armenian: 'Անտոնիոն ճաշից առաջ բացում է ութ կապույտ տուփ։',
  },
  {
    id: 11,
    spanish: 'Raúl corre rápido alrededor de las rocas del río.',
    armenian: 'Ռաուլը արագ վազում է գետի քարերի շուրջը։',
  },
  {
    id: 12,
    spanish: 'María mete muchas mandarinas maduras en una mochila marrón.',
    armenian: 'Մարիան շատ հասած մանդարիններ է դնում շագանակագույն պայուսակի մեջ։',
  },
  {
    id: 13,
    spanish: 'Diego dice diez dibujos distintos durante el desayuno.',
    armenian: 'Դիեգոն նախաճաշի ընթացքում նկարագրում է տասը տարբեր նկարներ։',
  },
  {
    id: 14,
    spanish: 'Beatriz busca botones blancos debajo de un banco.',
    armenian: 'Բեատրիսը նստարանի տակ սպիտակ կոճակներ է փնտրում։',
  },
  {
    id: 15,
    spanish: 'Elena elige enormes helados entre helados de fresa y limón.',
    armenian: 'Էլենան մեծ պաղպաղակներ է ընտրում ելակի և կիտրոնի պաղպաղակներից։',
  },
  {
    id: 16,
    spanish: 'Teresa trae tres tartas pequeñas para Tomás y Teresa.',
    armenian: 'Թերեսան երեք փոքր տորթ է բերում Թոմասի և իր համար։',
  },
  {
    id: 17,
    spanish: 'Gabriel guarda galletas grandes dentro de una gran caja.',
    armenian: 'Գաբրիելը մեծ թխվածքաբլիթներ է պահում մեծ տուփի մեջ։',
  },
  {
    id: 18,
    spanish: 'Pepe pela pequeñas patatas para Paula y Paco.',
    armenian: 'Պեպեն փոքր կարտոֆիլներ է մաքրում Պաուլայի և Պակոյի համար։',
  },
  {
    id: 19,
    spanish: 'Ricardo recoge ropa roja rápidamente mientras Raquel ríe.',
    armenian: 'Ռիկարդոն արագ հավաքում է կարմիր հագուստը, մինչ Ռաքելը ծիծաղում է։',
  },
  {
    id: 20,
    spanish: 'Sofía seca siete servilletas sobre seis sillas.',
    armenian: 'Սոֆիան յոթ անձեռոցիկ է չորացնում վեց աթոռների վրա։',
  },
  {
    id: 21,
    spanish: 'Bruno bebe batido de banana bajo un balcón blanco.',
    armenian: 'Բրունոն սպիտակ պատշգամբի տակ բանանի կոկտեյլ է խմում։',
  },
  {
    id: 22,
    spanish: 'Carmen corta cuatro calabazas con cuidado en la cocina.',
    armenian: 'Կարմենը խոհանոցում զգուշությամբ չորս դդում է կտրում։',
  },
  {
    id: 23,
    spanish: 'Nuria nota nueve nubes negras sobre Navarra.',
    armenian: 'Նուրիան Նավարայի վրա ինը սև ամպ է նկատում։',
  },
  {
    id: 24,
    spanish: 'Álvaro anda alegremente alrededor del árbol amarillo.',
    armenian: 'Ալվարոն ուրախ քայլում է դեղին ծառի շուրջը։',
  },
  {
    id: 25,
    spanish: 'Patricia prepara pequeños platos para Pedro y Pilar.',
    armenian: 'Պատրիսիան փոքր ափսեներ է պատրաստում Պեդրոյի և Պիլարի համար։',
  },
  {
    id: 26,
    spanish: 'Manuel mira muchas mariposas mientras mueve una manta.',
    armenian: 'Մանուելը շատ թիթեռների է նայում, մինչ վերմակն է շարժում։',
  },
  {
    id: 27,
    spanish: 'Rocío recoge rosas rojas para regalárselas a Rosa.',
    armenian: 'Ռոսիոն կարմիր վարդեր է հավաքում, որպեսզի նվիրի Ռոսային։',
  },
  {
    id: 28,
    spanish: 'Hugo hace ocho huevos hervidos a la hora del desayuno.',
    armenian: 'Ուգոն նախաճաշի ժամին ութ խաշած ձու է պատրաստում։',
  },
  {
    id: 29,
    spanish: 'Clara coloca cinco cucharas cerca de cuatro copas.',
    armenian: 'Կլարան հինգ գդալ է դնում չորս բաժակների մոտ։',
  },
  {
    id: 30,
    spanish: 'Iván invita a Irene a inventar historias interesantes.',
    armenian: 'Իվանը Իրենեին հրավիրում է հետաքրքիր պատմություններ հորինելու։',
  },
  {
    id: 31,
    spanish: 'Óscar observa ocho ovejas ordenadas junto al olivo.',
    armenian: 'Օսկարը ութ կարգավորված ոչխար է դիտում ձիթենու մոտ։',
  },
  {
    id: 32,
    spanish: 'Adrián abre alegremente armarios amarillos al amanecer.',
    armenian: 'Ադրիանը լուսաբացին ուրախ բացում է դեղին պահարանները։',
  },
  {
    id: 33,
    spanish: 'Inés intenta inflar nueve globos increíbles.',
    armenian: 'Ինեսը փորձում է փչել ինը զարմանալի փուչիկ։',
  },
  {
    id: 34,
    spanish: 'Víctor vende veinte vasos verdes los viernes.',
    armenian: 'Վիկտորը ուրբաթ օրերին քսան կանաչ բաժակ է վաճառում։',
  },
  {
    id: 35,
    spanish: 'Laura lava lentamente la lámpara larga del lavabo.',
    armenian: 'Լաուրան դանդաղ մաքրում է լվացարանի երկար լամպը։',
  },
  {
    id: 36,
    spanish: 'Pedro pinta puertas pequeñas de color púrpura.',
    armenian: 'Պեդրոն փոքր դռները մանուշակագույն է ներկում։',
  },
  {
    id: 37,
    spanish: 'Sara salta sobre seis sombras sin salir del sendero.',
    armenian: 'Սարան ցատկում է վեց ստվերների վրայով՝ առանց արահետից դուրս գալու։',
  },
  {
    id: 38,
    spanish: 'Tomás toma té templado todas las tardes.',
    armenian: 'Թոմասը ամեն կեսօր գոլ թեյ է խմում։',
  },
  {
    id: 39,
    spanish: 'Mónica mezcla melón, manzana y mango mientras merienda.',
    armenian: 'Մոնիկան խառնում է սեխ, խնձոր և մանգո՝ միջանկյալ սնունդ ուտելիս։',
  },
  {
    id: 40,
    spanish: 'Javier junta juguetes junto a Julia y Joaquín.',
    armenian: 'Խավիերը խաղալիքներ է հավաքում Խուլիայի և Խոակինի կողքին։',
  },
  {
    id: 41,
    spanish: 'Lorena lee largos libros los lunes por la tarde.',
    armenian: 'Լորենան երկուշաբթի կեսօրներին երկար գրքեր է կարդում։',
  },
  {
    id: 42,
    spanish: 'Pilar pela peras pequeñas para preparar un postre.',
    armenian: 'Պիլարը փոքր տանձեր է մաքրում՝ աղանդեր պատրաստելու համար։',
  },
  {
    id: 43,
    spanish: 'Samuel seca seis zapatos suaves bajo el sol.',
    armenian: 'Սամուելը արևի տակ չորացնում է վեց փափուկ կոշիկ։',
  },
  {
    id: 44,
    spanish: 'Gonzalo guarda grandes guantes grises en el garaje.',
    armenian: 'Գոնսալոն մեծ մոխրագույն ձեռնոցներ է պահում ավտոտնակում։',
  },
  {
    id: 45,
    spanish: 'Noelia nota nuevas noticias mientras navega por la noche.',
    armenian: 'Նոելիան գիշերը ինտերնետում շրջելիս նոր լուրեր է նկատում։',
  },
  {
    id: 46,
    spanish: 'Alicia arregla alegremente adornos azules antes de abril.',
    armenian: 'Ալիսիան ապրիլից առաջ ուրախությամբ կարգավորում է կապույտ զարդերը։',
  },
  {
    id: 47,
    spanish: 'Martín mueve muchas mesas mientras Marta mira maravillada.',
    armenian: 'Մարտինը շատ սեղաններ է շարժում, մինչ Մարտան զարմացած նայում է։',
  },
  {
    id: 48,
    spanish: 'Cristina corta cinco cocos con cuidado cerca de Carlos.',
    armenian: 'Կրիստինան Կառլոսի մոտ զգուշությամբ հինգ կոկոս է կտրում։',
  },
  {
    id: 49,
    spanish: 'Rubén rueda rápido alrededor de una roca redonda.',
    armenian: 'Ռուբենը արագ պտտվում է կլոր քարի շուրջը։',
  },
  {
    id: 50,
    spanish: 'Silvia sonríe mientras Sergio sirve sopa sobre siete servilletas.',
    armenian: 'Սիլվիան ժպտում է, մինչ Սերխիոն ապուր է մատուցում յոթ անձեռոցիկների վրա։',
  },
];
